### ISSUE TITLE
Not being able to remove the rate button and having the logo load every time I open the app are deal breakers

### ISSUE THREAD

**Issue by andreizet66** [JPTGamesAndApps/ShresthaFiles#7]
I was honestly going to buy this app, but not being able to remove the rate button will force me against this decision. I want an enhanced default experience, not to be constantly reminded that I'm using a third party app. 

Also, showing a huge logo on my screen and having to wait until the program loads only amplify the problem.

**Comment by JPTGamesAndApps** [comment]
Thank you for the feedback! I understand your notion. We will consider removing the rating button for paid users by default. Every rating help apps in the Store. Once rating is provided, the button will go away automatically. If you really want to remove the rate button, you can update the config file (when the app is closed): Change the value for "RatingsProvided" to true and the button will go away!

The startup screen is basically there as the program loads. Modern apps unfortunately take a while to load, and the startup screen is there just to let users know that the app is already loading. You might have noticed that quite a bit with apps for smartphones (and it's mostly the same reason).

Let us know if the information addresses the issue!

**Comment by andreizet66** [comment]
> Let us know if the information addresses the issue!

Yeah, thanks for the reply. I'll rate the app. After the trial I'll consider buying it. Happy to know there's a way to remove the rste button. Thanks for the info!
